#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <stdlib.h>

#include "parser.h"
#include "front.h"

static void error();

/* stmt
 * Parses strings in the language generated by the rule:
 * S ::= V:=E|read(V)|write(V)|while (C) do S od|O|S;S
 */
void stmt() 
{
    /* Parse read or write */
    if(nextToken == KEY_READ||nextToken == KEY_WRITE){
      lex();
        if (nextToken == LEFT_PAREN){
            lex();
            var();
        
          if (nextToken == RIGHT_PAREN)
              lex();
          else
              error();
        }
    }

    /*If starts with while*/
    else if(nextToken == KEY_WHILE){
        lex();
        if (nextToken == LEFT_PAREN){
            lex();
            c();}
        else
            error();
            if (nextToken == RIGHT_PAREN){
                lex();}
            else
                error();
                if (nextToken == KEY_DO){
                    lex();
                    stmt();}
                else
                    error();
                    if (nextToken == KEY_OD){
                        lex();}
    }

/*Differ between O and V:=E*/
    else if(nextToken==IDENT){
        var();
        if(nextToken==ASSIGN_OP){ //FOR V:=E
            lex();
            expr();
        }
        else if(nextToken==INC_OP||nextToken==DEC_OP){ //FINISH OFF O WITHOUT CALLING FUNCTION
            lex();
        }
        else
            error();
    }
    else if(nextToken==INC_OP||nextToken==DEC_OP){ //STARTS O IF SYMBOL STARTS IT
        lex();
        o();
    }

    if(nextToken==SEMICOLON){
        lex();
        stmt();
    }
} /* End of function stmt */

/* c
 * Parses strings in the language generated by the rule:
 * C ::= E<E|E>E|E=E|E!=E|E<=E|E>=E
 */

void c() 
{
  /* Parse the first term */
    expr();

    /* As long as the next token is in the language, get
    the next token and parse the next term */
    while (nextToken == LESSER_OP || nextToken == GREATER_OP|| nextToken == EQUAL_OP|| nextToken == NEQUAL_OP|| nextToken == LEQUAL_OP|| nextToken == GEQUAL_OP) {
        lex();
        expr();
    }
} /* End of function c */

/* expr
 * Parses strings in the language generated by the rule:
 * E ::= T|E+T|E-T
 */
void expr() 
{
    /* Parse the first term */
 term();
/* As long as the next token is + or -, get
 the next token and parse the next term */
 while (nextToken == ADD_OP || nextToken == SUB_OP) {
 lex();
 term();
 }
} /* End of function expr */

/* term
 * Parses strings in the language generated by the rule:
 * T ::= F|T*F|T/F
 */
void term() 
{
    /* Parse the first factor */
    factor();
    /* As long as the next token is * or /, get the
    next token and parse the next factor */
    while (nextToken == MULT_OP || nextToken == DIV_OP) {
        lex();
        factor();
    }
} /* End of function term */

/* factor
 * Parses strings in the language generated by the rule:
 * F ::= (E)|O|N|V
 * */
void factor() {

    /* CHECK FOR N */
    if (nextToken == INT_LIT)
        num();

    /* Differentiate between O and V */

    else if(nextToken==IDENT){
        var();
        if(nextToken==INC_OP||nextToken==DEC_OP){ //FINISH OFF O WITHOUT CALLING FUNCTION
            lex();
        }
    }
    else if(nextToken==INC_OP||nextToken==DEC_OP){ //STARTS O IF SYMBOL IS AT BEGINNING
        lex();
        o();
    }
    
    else {
        if (nextToken == LEFT_PAREN) {
            lex();
            expr();
            if (nextToken == RIGHT_PAREN)
                lex();
            else
                error();
        } /* End of if (nextToken == ... */
    } /* End of else */
} /* End of function factor */

/* o
 * Parses strings in the language generated by the rule:
 * O ::= V++|V--|++V|--V
 */

void o() {
    var();
} /* End of function o */

/* var
 * Parses strings in the language generated by the rule:
 * V ::= a|b|...|y|z|aV|bV|...|yV|zV
 */

void var() {
   lex();
} /* End of function var */

/* num
 * Parses strings in the language generated by the rule:
 * N ::= 0|1|...|8|9|0N|1N|...|8N|9N
 */

void num() {
    lex();
} /* End of function num */

static void error() 
{
    printf("Error (more is desired, but not implemented).\n");
